// ============================================
// FILE GENERATOR MODULE
// Generate PDF, DOCX, PPTX, Code Files, Projects
// ============================================

const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun } = require('docx');
const pptxgen = require('pptxgenjs');
const JSZip = require('jszip');
const admin = require('firebase-admin');
const fs = require('fs');
const path = require('path');
const { Readable } = require('stream');

// Initialize Firebase Admin (if not already initialized)
if (!admin.apps.length) {
    try {
        admin.initializeApp({
            credential: admin.credential.applicationDefault(),
            storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'vishai-f6197.appspot.com'
        });
        console.log('✅ Firebase Admin initialized for file generation');
    } catch (error) {
        console.log('⚠️ Firebase Admin initialization skipped:', error.message);
    }
}

// ============================================
// PDF GENERATION
// ============================================
async function createPdf(content, filename) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 50, bottom: 50, left: 50, right: 50 }
            });

            const chunks = [];
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // Add header
            doc.fontSize(24)
               .fillColor('#667eea')
               .text('JARVIS AI', { align: 'center' });
            
            doc.moveDown();
            doc.fontSize(18)
               .fillColor('#333333')
               .text(filename.replace('.pdf', ''), { align: 'center' });
            
            doc.moveDown(2);

            // Add content
            doc.fontSize(12)
               .fillColor('#000000')
               .text(content, {
                   align: 'left',
                   lineGap: 5
               });

            // Add footer
            doc.moveDown(2);
            doc.fontSize(10)
               .fillColor('#888888')
               .text(`Generated by JARVIS AI on ${new Date().toLocaleString()}`, {
                   align: 'center'
               });

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

// ============================================
// DOCX GENERATION
// ============================================
async function createDocx(content, filename) {
    try {
        const paragraphs = content.split('\n').map(line => 
            new Paragraph({
                children: [
                    new TextRun({
                        text: line || ' ',
                        size: 24 // 12pt
                    })
                ],
                spacing: { after: 200 }
            })
        );

        // Add header
        const headerParagraphs = [
            new Paragraph({
                children: [
                    new TextRun({
                        text: 'JARVIS AI',
                        bold: true,
                        size: 32,
                        color: '667eea'
                    })
                ],
                spacing: { after: 400 }
            }),
            new Paragraph({
                children: [
                    new TextRun({
                        text: filename.replace('.docx', ''),
                        bold: true,
                        size: 28
                    })
                ],
                spacing: { after: 600 }
            })
        ];

        // Add footer
        const footerParagraphs = [
            new Paragraph({
                children: [
                    new TextRun({
                        text: `\nGenerated by JARVIS AI on ${new Date().toLocaleString()}`,
                        size: 20,
                        color: '888888',
                        italics: true
                    })
                ]
            })
        ];

        const doc = new Document({
            sections: [{
                children: [...headerParagraphs, ...paragraphs, ...footerParagraphs]
            }]
        });

        const buffer = await Packer.toBuffer(doc);
        return buffer;
    } catch (error) {
        throw new Error(`DOCX generation failed: ${error.message}`);
    }
}

// ============================================
// PPTX GENERATION
// ============================================
async function createPptx(content, filename) {
    try {
        const pptx = new pptxgen();

        // Title slide
        const titleSlide = pptx.addSlide();
        titleSlide.background = { color: '667eea' };
        titleSlide.addText('JARVIS AI', {
            x: 1,
            y: 1.5,
            w: 8,
            h: 1,
            fontSize: 44,
            bold: true,
            color: 'FFFFFF',
            align: 'center'
        });
        titleSlide.addText(filename.replace('.pptx', ''), {
            x: 1,
            y: 2.8,
            w: 8,
            h: 0.8,
            fontSize: 28,
            color: 'FFFFFF',
            align: 'center'
        });

        // Split content into slides (every 300 characters or by paragraphs)
        const sections = content.split('\n\n').filter(s => s.trim());
        const slidesData = [];
        let currentSlideText = '';

        for (const section of sections) {
            if ((currentSlideText + section).length > 300 && currentSlideText) {
                slidesData.push(currentSlideText);
                currentSlideText = section;
            } else {
                currentSlideText += (currentSlideText ? '\n\n' : '') + section;
            }
        }
        if (currentSlideText) slidesData.push(currentSlideText);

        // Content slides
        slidesData.forEach((text, index) => {
            const slide = pptx.addSlide();
            slide.addText(`Slide ${index + 1}`, {
                x: 0.5,
                y: 0.5,
                w: 9,
                h: 0.5,
                fontSize: 24,
                bold: true,
                color: '667eea'
            });
            slide.addText(text, {
                x: 0.5,
                y: 1.2,
                w: 9,
                h: 4.5,
                fontSize: 16,
                color: '000000',
                valign: 'top'
            });
        });

        // Footer slide
        const footerSlide = pptx.addSlide();
        footerSlide.addText('Generated by JARVIS AI', {
            x: 1,
            y: 2.5,
            w: 8,
            h: 1,
            fontSize: 20,
            color: '888888',
            align: 'center',
            italic: true
        });
        footerSlide.addText(new Date().toLocaleString(), {
            x: 1,
            y: 3.2,
            w: 8,
            h: 0.5,
            fontSize: 14,
            color: '888888',
            align: 'center'
        });

        // Generate buffer
        const buffer = await pptx.write({ outputType: 'nodebuffer' });
        return buffer;
    } catch (error) {
        throw new Error(`PPTX generation failed: ${error.message}`);
    }
}

// ============================================
// CODE FILE GENERATION
// ============================================
async function createCodeFile(content, filename) {
    try {
        const buffer = Buffer.from(content, 'utf-8');
        return buffer;
    } catch (error) {
        throw new Error(`Code file generation failed: ${error.message}`);
    }
}

// ============================================
// PROJECT ZIP GENERATION
// ============================================
async function createProjectZip(projectType, projectName) {
    try {
        const zip = new JSZip();

        if (projectType === 'react') {
            // React Starter Project
            zip.file('package.json', JSON.stringify({
                name: projectName,
                version: '1.0.0',
                private: true,
                dependencies: {
                    'react': '^18.2.0',
                    'react-dom': '^18.2.0',
                    'react-scripts': '5.0.1'
                },
                scripts: {
                    'start': 'react-scripts start',
                    'build': 'react-scripts build',
                    'test': 'react-scripts test',
                    'eject': 'react-scripts eject'
                }
            }, null, 2));

            zip.folder('public').file('index.html', `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${projectName}</title>
</head>
<body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
</body>
</html>`);

            zip.folder('src').file('index.js', `import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`);

            zip.folder('src').file('App.js', `import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to ${projectName}</h1>
        <p>Generated by JARVIS AI</p>
      </header>
    </div>
  );
}

export default App;`);

            zip.folder('src').file('App.css', `.App {
  text-align: center;
}

.App-header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}`);

            zip.folder('src').file('index.css', `body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}`);

            zip.file('README.md', `# ${projectName}

Generated by JARVIS AI on ${new Date().toLocaleString()}

## Getting Started

1. Install dependencies:
\`\`\`
npm install
\`\`\`

2. Start the development server:
\`\`\`
npm start
\`\`\`

3. Open [http://localhost:3000](http://localhost:3000) to view it in your browser.

## Available Scripts

- \`npm start\` - Runs the app in development mode
- \`npm build\` - Builds the app for production
- \`npm test\` - Launches the test runner

Built with ❤️ by JARVIS AI`);

        } else if (projectType === 'node') {
            // Node.js Starter Project
            zip.file('package.json', JSON.stringify({
                name: projectName,
                version: '1.0.0',
                description: 'Node.js project generated by JARVIS AI',
                main: 'index.js',
                scripts: {
                    'start': 'node index.js',
                    'dev': 'nodemon index.js'
                },
                dependencies: {
                    'express': '^4.18.2',
                    'cors': '^2.8.5',
                    'dotenv': '^16.3.1'
                },
                devDependencies: {
                    'nodemon': '^3.0.1'
                }
            }, null, 2));

            zip.file('index.js', `const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Routes
app.get('/', (req, res) => {
  res.json({ 
    message: 'Welcome to ${projectName}',
    generatedBy: 'JARVIS AI',
    timestamp: new Date().toISOString()
  });
});

app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', uptime: process.uptime() });
});

// Start server
app.listen(PORT, () => {
  console.log(\`✅ Server running on http://localhost:\${PORT}\`);
});`);

            zip.file('.env', `PORT=3000
NODE_ENV=development`);

            zip.file('README.md', `# ${projectName}

Node.js Express server generated by JARVIS AI on ${new Date().toLocaleString()}

## Getting Started

1. Install dependencies:
\`\`\`
npm install
\`\`\`

2. Start the server:
\`\`\`
npm start
\`\`\`

3. For development with auto-reload:
\`\`\`
npm run dev
\`\`\`

## API Endpoints

- \`GET /\` - Welcome message
- \`GET /api/health\` - Health check

Built with ❤️ by JARVIS AI`);

        } else {
            throw new Error('Invalid project type. Use "react" or "node"');
        }

        const buffer = await zip.generateAsync({ type: 'nodebuffer' });
        return buffer;
    } catch (error) {
        throw new Error(`Project ZIP generation failed: ${error.message}`);
    }
}

// ============================================
// FIREBASE STORAGE UPLOAD
// ============================================
async function uploadToFirebase(buffer, filename, mimeType) {
    try {
        const bucket = admin.storage().bucket();
        const file = bucket.file(`generated-files/${Date.now()}-${filename}`);

        await file.save(buffer, {
            metadata: {
                contentType: mimeType,
                metadata: {
                    generatedBy: 'JARVIS AI',
                    timestamp: new Date().toISOString()
                }
            }
        });

        // Make file publicly accessible
        await file.makePublic();

        // Get download URL
        const downloadUrl = `https://storage.googleapis.com/${bucket.name}/${file.name}`;
        
        return downloadUrl;
    } catch (error) {
        throw new Error(`Firebase upload failed: ${error.message}`);
    }
}

// ============================================
// MAIN HANDLER
// ============================================
async function generateFile(type, content, filename, projectType = 'react') {
    try {
        let buffer;
        let mimeType;
        let generatedFilename = filename;

        switch (type) {
            case 'pdf':
                buffer = await createPdf(content, filename);
                mimeType = 'application/pdf';
                if (!generatedFilename.endsWith('.pdf')) generatedFilename += '.pdf';
                break;

            case 'docx':
                buffer = await createDocx(content, filename);
                mimeType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
                if (!generatedFilename.endsWith('.docx')) generatedFilename += '.docx';
                break;

            case 'pptx':
                buffer = await createPptx(content, filename);
                mimeType = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
                if (!generatedFilename.endsWith('.pptx')) generatedFilename += '.pptx';
                break;

            case 'code':
                buffer = await createCodeFile(content, filename);
                mimeType = getMimeTypeFromExtension(filename);
                break;

            case 'project':
                buffer = await createProjectZip(projectType, filename);
                mimeType = 'application/zip';
                if (!generatedFilename.endsWith('.zip')) generatedFilename += '.zip';
                break;

            default:
                throw new Error('Invalid file type. Use: pdf, docx, pptx, code, or project');
        }

        // Upload to Firebase Storage
        const downloadUrl = await uploadToFirebase(buffer, generatedFilename, mimeType);

        return {
            success: true,
            filename: generatedFilename,
            url: downloadUrl,
            size: buffer.length,
            type: mimeType
        };
    } catch (error) {
        throw error;
    }
}

// Helper function to get MIME type from file extension
function getMimeTypeFromExtension(filename) {
    const ext = filename.split('.').pop().toLowerCase();
    const mimeTypes = {
        'js': 'text/javascript',
        'py': 'text/x-python',
        'html': 'text/html',
        'css': 'text/css',
        'json': 'application/json',
        'xml': 'application/xml',
        'java': 'text/x-java',
        'c': 'text/x-c',
        'cpp': 'text/x-c++',
        'cs': 'text/x-csharp',
        'php': 'text/x-php',
        'rb': 'text/x-ruby',
        'go': 'text/x-go',
        'rs': 'text/x-rust',
        'swift': 'text/x-swift',
        'kt': 'text/x-kotlin',
        'ts': 'text/typescript',
        'jsx': 'text/jsx',
        'tsx': 'text/tsx',
        'md': 'text/markdown',
        'txt': 'text/plain'
    };
    return mimeTypes[ext] || 'text/plain';
}

module.exports = {
    createPdf,
    createDocx,
    createPptx,
    createCodeFile,
    createProjectZip,
    uploadToFirebase,
    generateFile
};
